main/app/urls.py
from django.urls import path, include
from rest_framework import routers

from .views import PostViewSet, CommentsViewSet, main_page, UpvotePostView

app_name = "app"

router = routers.DefaultRouter()
router.register(r"posts", PostViewSet, basename="posts")
router.register(r"comments", CommentsViewSet, basename="comments")

urlpatterns = [
    path("", main_page, name="main_page"),
    path("api/", include(router.urls)),
    path("api/posts/<int:post_id>/upvote", UpvotePostView.as_view()),
]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("app/", include("app.urls")),
]

main/app/models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=64,
                             verbose_name="Заголовок поста")
    link = models.URLField(verbose_name="Ссылка на новость")
    creation_date = models.DateField(auto_now_add=True,
                                     verbose_name="Дата создания")
    amount_of_upvotes = models.IntegerField(verbose_name="Апвоут")
    author_name = models.CharField(max_length=64,
                                   verbose_name="Имя автора")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"
        ordering = ["-creation_date"]


class Comment(models.Model):
    author_name = models.CharField(max_length=64,
                                   verbose_name="Автор комментария")
    content = models.TextField(max_length=512,
                               verbose_name="Тело комментария")
    creation_date = models.DateField(auto_now_add=True,
                                     verbose_name="Дата создания")
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name="comments",
                             verbose_name="Пост")

    def __str__(self):
        return f"{self.post} | {self.author_name}"

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"
        ordering = ["-creation_date"]

main/app/views.py
from django.shortcuts import render
from rest_framework import status
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework.viewsets import ModelViewSet

from .models import Post, Comment
from .serializers import PostSerializer, CommentSerializer


def main_page(request):
    posts = Post.objects.all()
    return render(request, "main.html", {"posts": posts})


class PostViewSet(ModelViewSet):
    queryset = Post.objects.all()
    serializer_class = PostSerializer


class CommentsViewSet(ModelViewSet):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer


class UpvotePostView(APIView):
    def get(self, request, post_id):
        post = Post.objects.get(id=post_id)
        post.amount_of_upvotes += 1
        post.save()
        return Response({"message": "Post Upvoted"}, status=status.HTTP_200_OK)

main/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title>Main page</title>
</head>
<body>
<header>
    <ul class="nav">
        <li><a href="{% url 'app:main_page'%}">Новости</a></li>
        <li><a href="./api">API</a></li>
    </ul>
</header>
<main>
    {% for post in posts %}
    <div class="post">
        <div class="upvote"><a href="api/posts/{{ post.id }}/upvote">UP</a></div>
        <div class="title">{{ post.title }}</div>
        <div class="body"><a href="{{ post.link }}">Ссылка</a></div>
        <div class="info">
            <p>{{ post.author_name }}</p>
            <p>{{ post.creation_date }}</p>
            <p>{{ post.amount_of_upvotes }}</p>
        </div>
        <hr/>
    </div>
    {% endfor %}
</main>
<footer>
    <p>Made by <a class="gitlink" href="https://github.com/Neekeech24" target="_blank">Neekeech</a></p>
</footer>
</body>
</html>